export default {
  1: 'Install Tailwind CSS without any Javascript Framework locally with purgeCSS, enable the dark mode option, preferences or class is up to you.',
  2: 'Write some text including headings and subheadings, quotes, italics. Train your typography.',
  3: 'Create state buttons with a hover and a transition effect, like primary button, secondary and for example disable.',
  4: 'Create and rework a select element including options and style it with only Tailwind.',
  5: 'Create a form with buttons, inputs and text areas. Remember the download and upload buttons, those can be also included. And center it in the middle. Make it responsive.',
  6: 'Create an avatar inside a card along with some text, and make it 100% reponsive.',
  7: 'Create a navigation bar with logo, links and a CTA. Make it fixed, sticky or normal.',
  8: 'Create a grid with columns and rows, use tailwinds flexbox utilities make it responsive.',
  9: 'Create a 5 widget and position them differently on the website.',
  10: 'Make a card with and image and text. The text has to be on top of the image, use absolute and relative.',
  11: 'Make some sections and a container within and give them different widths and heights.',
  12: 'Create a section with an image, with text to the right, left or underneath or on top of it. Make it responsive.',
  13: 'Create a footer layout with links and logo. Remember the white space and to make it responsive.',
  14: 'Create a sidebar, fixed, sticky or normal. include links and a top logo.',
  15: 'Make sidebar layout with left or right scrollable content.',
  16: 'Create your color, font and shadow themes within the tailwind.config.js and use them on any layout you created before. Give them custom names.',
  17: 'Create a kan ban layout, with cards and boxes and make it responsive.',
  18: 'Make a dropdown with links and icons. You can use Alpine.js too, why not.',
  19: 'Make a dropdown with two columns, links and icons. Make it responsive.',
  20: 'Create a layout, any of your choice. Use your creations as content, make it responsive.',
  21: 'Create a horizontal scrollable layout only using Tailwind CSS, for example a card row and make it responsive.',
  22: 'Create a full width and height grid of two columns and 5 rows, make it responsive.',
  23: 'Create a grid with cards for your team and make them responsive, include a picture, name and twitter.',
  24: 'Create a grid layout with cards, give them different widths and heights.',
  25: 'Create notifications for a few states with a close icon. Make it work with Alpine.js',
  26: 'Create some cards and give them different Tailwind gradients.',
  27: 'Make some headings and give them a gradient color, use bg-clip-text .',
  28: 'Create pagination widgets. With a button group, separated and side to side.',
  29: 'Create a pricing table with three or more cards, make this ones responsive.',
  30: 'Re-create your favourite UI or a whole website only using Tailwind.',
};
